### ISSUE TITLE
Localize the project website into Mandarin Chinese

### ISSUE THREAD

**Issue by lopopolo** [artichoke/www.artichokeruby.org#437]
Per Google Analytics, visitors from China account for about 30% of traffic.

One of the top referrers is a request to translate the site into `zh` locale.

See https://twitter.com/artichokeruby/status/1464440133923459072?s=21.

**Comment by ecnelises** [comment]
I'd like to have a try :)

**Comment by lopopolo** [comment]
Awesome thank you @ecnelises

**Comment by renny-ren** [comment]
created a pull request #448 and it is working in progress.

**Comment by lopopolo** [comment]
This is complete as of:

- #449
- #472
- #475 

Thanks everyone for your help!
